### ISSUE TITLE
How to use White for no data vs Black

### ISSUE THREAD

**Issue by jasonfish** [WKHarmon/led-sectional#6]
I'd like to have stations display white (or any other color, really) when there's no valid weather report, rather than turn off. Winds and lightning are both false.

I've changed the following lines:
fill_solid(leds, NUM_AIRPORTS, CRGB::White);
and
} else color = CRGB::White;

I've also tried Aqua, just for giggles. When changing a known-good station name to an invalid string, like KSEAo, the LED just shuts off.

Tips?

**Comment by WKHarmon** [comment]
I suspect that the problem is the `FastLED.clear();` on line 347. Try adding `fill_solid(leds, NUM_AIRPORTS, CRGB::White);` immediately after that. My guess is that the earlier fill_solid actually doesn't do anything because of the clear later. Unfortunately, I'm not somewhere that I can test it readily at the moment.

The `} else color = CRGB::White;` on line 482 will only trigger if there is actually a METAR returned by the API for that airport, but there was no flight category returned, so it probably won't happen much.

**Comment by jasonfish** [comment]
That did it. Thanks!

**Comment by a-sp** [comment]
Would you consider making this behavior configurable in the software?

It would be helpful to have an option to define what color is shown when there is no valid weather report, rather than hard-coding the behavior. That way users could choose between LED off, white, or another color. Thanks!

**Comment by WKHarmon** [comment]
Added in release [2.0.8](https://github.com/WKHarmon/led-sectional/releases/tag/v2.0.8). You'll find the new setting in the Advanced section of the configuration utility. You'll need to update to the latest firmware before it works.

**Comment by a-sp** [comment]
Hi @WKHarmon thank you very much for the incredibly fast implementation of this feature! I really appreciate your responsiveness and support for the project!

I wanted to ask if it might be possible to refine the manual color override behavior a bit further.

At the moment, the manually defined color seems to apply both to:
- Airports with no available weather report
- LEDs where the airport value is explicitly set to NULL

Would it be possible to have the manual color apply only to airports with no weather report available, while LEDs configured as NULL remain off / disabled as they are conceptually “unused”?

That would make the distinction clearer when using spare LEDs or intentional empty positions on the map.

Thanks again for the great work!

**Comment by WKHarmon** [comment]
Oops, that was definitely a mistake. I re-released 2.0.8 with that bugfix. If you install the firmware again it should pick up the new behavior, but if it doesn't let me know.

**Comment by a-sp** [comment]
I reinstalled the firmware and tested it, and now everything works beautifully! Thank you again for the incredibly fast support!
