### ISSUE TITLE
Flight category "WVFR"?

### ISSUE THREAD

**Issue by b-hud** [WKHarmon/led-sectional#9]
Not finding any documentation on what flight category "WVFR" means.

[context](https://www.aviationweather.gov/taf/help?page=plot)

**Comment by WKHarmon** [comment]
There's a little bit of detail about it here, although I don't call it out explicitly: https://led-sectional.kyleharmon.com/#software

It's basically something I made up called "windy VFR", which is VFR conditions with winds above the threshold defined in `#define WIND_THRESHOLD`. I created just to make things a bit more interesting in the summer because my own map is for California, which would be super boring 6 months out of the year.

**Comment by b-hud** [comment]
Gotcha, thanks for clarifying. I saw the code about the wind conditions but didn't make the connection.

Side note, your code worked great on my project and your tutorial was awesome. Thanks so much.
